require 'json'

package = JSON.parse(File.read(File.join(__dir__, 'package.json')))

Pod::Spec.new do |s|
  s.name           = 'KycSdkReactNative'
  s.version        = package['version']
  s.summary        = package['description']
  s.license        = package['license']
  s.author         = 'Myaza'
  s.homepage       = 'https://github.com/myazahq/kyc-sdk-react-native'
  s.platforms      = { :ios => '15.1' }
  s.swift_version  = '5.9'
  s.source         = { :git => 'https://github.com/myazahq/kyc-sdk-react-native.git', :tag => "#{s.version}" }

  # Apple Vision face-detector — a VisionCamera v5 Nitro HybridObject
  # (ios/HybridMyazaFaceDetector.swift), generated from
  # src/specs/MyazaFaceDetector.nitro.ts. No GoogleMLKit pod — iOS uses Vision,
  # so the SDK still builds on Apple-Silicon iOS simulators.
  s.source_files = 'ios/**/*.{h,m,mm,swift}'

  s.dependency 'React-Core'
  s.dependency 'VisionCamera'

  # Add all files generated by Nitrogen (the C++/Swift specs, the Swift↔C++
  # bridge, and the C++20 / SWIFT_OBJC_INTEROP_MODE=objcxx build settings the
  # Nitro HybridObject needs) and the NitroModules dependency. Registration is
  # handled by Nitro autolinking — no ObjC `+load` macro, so the old `-ObjC`
  # dead-strip workaround is gone.
  load 'nitrogen/generated/ios/KycSdkReactNative+autolinking.rb'
  add_nitrogen_files(s)
end
