// GENERATED — do not edit by hand.
//
// ISO-3166 alpha-2 country names, generated FROM the Flutter SDK's
// country_names.g.dart so both SDKs label a country identically by
// construction rather than by two runtimes happening to agree.
//
// This exists because `Intl.DisplayNames` is not dependable here: Hermes may
// ship without the region data, and when it does every row in the picker reads
// as a bare ISO code ("NG" instead of "Nigeria"). A table is a few KB and it
// always works.

export const COUNTRY_NAMES: Record<string, string> = {
  DZ: 'Algeria',
  AO: 'Angola',
  BJ: 'Benin',
  BW: 'Botswana',
  BF: 'Burkina Faso',
  BI: 'Burundi',
  CV: 'Cape Verde',
  CM: 'Cameroon',
  CF: 'Central African Republic',
  TD: 'Chad',
  KM: 'Comoros',
  CG: 'Congo - Brazzaville',
  CD: 'Congo - Kinshasa',
  CI: 'Côte d’Ivoire',
  DJ: 'Djibouti',
  EG: 'Egypt',
  GQ: 'Equatorial Guinea',
  ER: 'Eritrea',
  SZ: 'Eswatini',
  ET: 'Ethiopia',
  GA: 'Gabon',
  GM: 'Gambia',
  GH: 'Ghana',
  GN: 'Guinea',
  GW: 'Guinea-Bissau',
  KE: 'Kenya',
  LS: 'Lesotho',
  LR: 'Liberia',
  LY: 'Libya',
  MG: 'Madagascar',
  MW: 'Malawi',
  ML: 'Mali',
  MR: 'Mauritania',
  MU: 'Mauritius',
  YT: 'Mayotte',
  MA: 'Morocco',
  MZ: 'Mozambique',
  NA: 'Namibia',
  NE: 'Niger',
  NG: 'Nigeria',
  RE: 'Réunion',
  RW: 'Rwanda',
  SH: 'St. Helena',
  ST: 'São Tomé & Príncipe',
  SN: 'Senegal',
  SC: 'Seychelles',
  SL: 'Sierra Leone',
  SO: 'Somalia',
  ZA: 'South Africa',
  SS: 'South Sudan',
  SD: 'Sudan',
  TZ: 'Tanzania',
  TG: 'Togo',
  TN: 'Tunisia',
  UG: 'Uganda',
  EH: 'Western Sahara',
  ZM: 'Zambia',
  ZW: 'Zimbabwe',
  AE: 'United Arab Emirates',
  BH: 'Bahrain',
  IL: 'Israel',
  IQ: 'Iraq',
  IR: 'Iran',
  JO: 'Jordan',
  KW: 'Kuwait',
  LB: 'Lebanon',
  OM: 'Oman',
  PS: 'Palestinian Territories',
  QA: 'Qatar',
  SA: 'Saudi Arabia',
  SY: 'Syria',
  TR: 'Türkiye',
  YE: 'Yemen',
  AD: 'Andorra',
  AL: 'Albania',
  AT: 'Austria',
  AX: 'Åland Islands',
  BA: 'Bosnia & Herzegovina',
  BE: 'Belgium',
  BG: 'Bulgaria',
  BY: 'Belarus',
  CH: 'Switzerland',
  CY: 'Cyprus',
  CZ: 'Czechia',
  DE: 'Germany',
  DK: 'Denmark',
  EE: 'Estonia',
  ES: 'Spain',
  FI: 'Finland',
  FO: 'Faroe Islands',
  FR: 'France',
  GB: 'United Kingdom',
  GG: 'Guernsey',
  GI: 'Gibraltar',
  GR: 'Greece',
  HR: 'Croatia',
  HU: 'Hungary',
  IE: 'Ireland',
  IM: 'Isle of Man',
  IS: 'Iceland',
  IT: 'Italy',
  JE: 'Jersey',
  LI: 'Liechtenstein',
  LT: 'Lithuania',
  LU: 'Luxembourg',
  LV: 'Latvia',
  MC: 'Monaco',
  MD: 'Moldova',
  ME: 'Montenegro',
  MK: 'North Macedonia',
  MT: 'Malta',
  NL: 'Netherlands',
  NO: 'Norway',
  PL: 'Poland',
  PT: 'Portugal',
  RO: 'Romania',
  RS: 'Serbia',
  RU: 'Russia',
  SE: 'Sweden',
  SI: 'Slovenia',
  SJ: 'Svalbard & Jan Mayen',
  SK: 'Slovakia',
  SM: 'San Marino',
  UA: 'Ukraine',
  VA: 'Vatican City',
  XK: 'Kosovo',
  AG: 'Antigua & Barbuda',
  AI: 'Anguilla',
  AR: 'Argentina',
  AW: 'Aruba',
  BB: 'Barbados',
  BL: 'St. Barthélemy',
  BM: 'Bermuda',
  BO: 'Bolivia',
  BQ: 'Caribbean Netherlands',
  BR: 'Brazil',
  BS: 'Bahamas',
  BZ: 'Belize',
  CA: 'Canada',
  CL: 'Chile',
  CO: 'Colombia',
  CR: 'Costa Rica',
  CU: 'Cuba',
  CW: 'Curaçao',
  DM: 'Dominica',
  DO: 'Dominican Republic',
  EC: 'Ecuador',
  FK: 'Falkland Islands',
  GD: 'Grenada',
  GF: 'French Guiana',
  GL: 'Greenland',
  GP: 'Guadeloupe',
  GT: 'Guatemala',
  GY: 'Guyana',
  HN: 'Honduras',
  HT: 'Haiti',
  JM: 'Jamaica',
  KN: 'St. Kitts & Nevis',
  KY: 'Cayman Islands',
  LC: 'St. Lucia',
  MF: 'St. Martin',
  MQ: 'Martinique',
  MS: 'Montserrat',
  MX: 'Mexico',
  NI: 'Nicaragua',
  PA: 'Panama',
  PE: 'Peru',
  PM: 'St. Pierre & Miquelon',
  PR: 'Puerto Rico',
  PY: 'Paraguay',
  SR: 'Suriname',
  SV: 'El Salvador',
  SX: 'Sint Maarten',
  TC: 'Turks & Caicos Islands',
  TT: 'Trinidad & Tobago',
  US: 'United States',
  UY: 'Uruguay',
  VC: 'St. Vincent & Grenadines',
  VE: 'Venezuela',
  VG: 'British Virgin Islands',
  VI: 'U.S. Virgin Islands',
  AF: 'Afghanistan',
  AM: 'Armenia',
  AS: 'American Samoa',
  AU: 'Australia',
  AZ: 'Azerbaijan',
  BD: 'Bangladesh',
  BN: 'Brunei',
  BT: 'Bhutan',
  CK: 'Cook Islands',
  CN: 'China',
  FJ: 'Fiji',
  FM: 'Micronesia',
  GE: 'Georgia',
  GU: 'Guam',
  HK: 'Hong Kong SAR China',
  ID: 'Indonesia',
  IN: 'India',
  JP: 'Japan',
  KG: 'Kyrgyzstan',
  KH: 'Cambodia',
  KI: 'Kiribati',
  KP: 'North Korea',
  KR: 'South Korea',
  KZ: 'Kazakhstan',
  LA: 'Laos',
  LK: 'Sri Lanka',
  MH: 'Marshall Islands',
  MM: 'Myanmar (Burma)',
  MN: 'Mongolia',
  MO: 'Macao SAR China',
  MP: 'Northern Mariana Islands',
  MV: 'Maldives',
  MY: 'Malaysia',
  NC: 'New Caledonia',
  NF: 'Norfolk Island',
  NP: 'Nepal',
  NR: 'Nauru',
  NU: 'Niue',
  NZ: 'New Zealand',
  PF: 'French Polynesia',
  PG: 'Papua New Guinea',
  PH: 'Philippines',
  PK: 'Pakistan',
  PN: 'Pitcairn Islands',
  PW: 'Palau',
  SB: 'Solomon Islands',
  SG: 'Singapore',
  TH: 'Thailand',
  TJ: 'Tajikistan',
  TK: 'Tokelau',
  TL: 'Timor-Leste',
  TM: 'Turkmenistan',
  TO: 'Tonga',
  TV: 'Tuvalu',
  TW: 'Taiwan',
  UZ: 'Uzbekistan',
  VN: 'Vietnam',
  VU: 'Vanuatu',
  WF: 'Wallis & Futuna',
  WS: 'Samoa',
};
