/**
 * The icon roles this SDK draws, by MEANING rather than by glyph name.
 *
 * This is the boundary that lets the set underneath change without touching a
 * call site: a screen asks for 'close', and `icons/map.ts` decides what that
 * looks like. Adding a role here means adding its glyph there.
 */

export type IconName =
  // chrome
  | 'close'
  | 'back'
  | 'moon'
  | 'sun'
  | 'check'
  | 'lock'
  | 'alert'
  | 'flask'
  | 'refresh'
  | 'refresh-ccw'
  | 'maximize'
  | 'calendar'
  | 'image'
  | 'chevron-left'
  | 'chevron-right'
  | 'chevron-down'
  // consent hero + process steps
  | 'shield'
  | 'badge-check'
  | 'circle-dashed'
  | 'circle-check'
  | 'circle-help'
  | 'circle-x'
  | 'building-2'
  | 'stamp'
  | 'user'
  | 'user-plus'
  | 'plus'
  | 'info'
  | 'users'
  | 'scan-line'
  | 'scan-face'
  | 'nfc'
  | 'filter'
  | 'pencil'
  | 'pencil-line'
  | 'search'
  | 'zap'
  | 'link'
  | 'copy'
  | 'share'
  | 'zap-off'
  | 'timer'
  // id-type glyphs
  | 'fingerprint'
  | 'credit-card'
  | 'globe'
  | 'car'
  | 'vote'
  | 'file-text'
  | 'house'
  | 'landmark'
  | 'id-card'
  | 'contact'
  | 'passport'
  | 'camera'
  | 'camera-off'
  | 'video-off'
  | 'upload'
  | 'x'
  // address collection (map picker + the presence milestone track)
  | 'map-pin'
  | 'map-pin-house'
  | 'map-pin-check'
  | 'map-pinned'
  | 'radar'
  | 'bell-ring'
  | 'sliders'
  | 'locate'
  | 'minus'
  | 'lightbulb'
  // contact verification (OTP channels + step footer)
  | 'mail'
  | 'smartphone'
  | 'message-square'
  | 'message-circle';
